# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: List repo files

on: push

jobs:
  list-files:

    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        run: git clone https://github.com/simaz33/NewLanguage
        
      - name: List repo files
        working-directory: NewLanguage
        run: git status
#    - uses: actions/checkout@v2
